### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by marc-** [mkorpela/RoboMachine#19]
RoboMachine installation via pip (within virtualenv) fails due to missing dependencies.
```
Downloading/unpacking RoboMachine
  Downloading RoboMachine-0.7.tar.gz
  Running setup.py (path:/tmp/pip-build-THNdGc/RoboMachine/setup.py) egg_info for package RoboMachine
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-THNdGc/RoboMachine/setup.py", line 6, in <module>
        import robomachine
      File "robomachine/__init__.py", line 16, in <module>
        from parsing import parse
      File "robomachine/parsing.py", line 15, in <module>
        from pyparsing import *
    ImportError: No module named pyparsing
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-THNdGc/RoboMachine/setup.py", line 6, in <module>

    import robomachine

  File "robomachine/__init__.py", line 16, in <module>

    from parsing import parse

  File "robomachine/parsing.py", line 15, in <module>

    from pyparsing import *

ImportError: No module named pyparsing
```

See
https://github.com/mkorpela/RoboMachine/blob/master/setup.py#L6
https://github.com/mkorpela/RoboMachine/blob/master/setup.py#L13

Proposal: 
`version` needs to be moved into seprate module without external dependencies.

**Comment by mkorpela** [comment]
Nope. Not gona happen. Either you've fixed the dependency problem by installing that dependency or your just trying to get your license text to the codebase.

**Comment by marc-** [comment]
Dependency is required and pip supposed to take care of that. You test it yourself using virtualenv this way (assuming we're in project root folder):
```
$ virtualenv ../venv
$ ../venv/bin/pip install ./
$ ../venv/bin/pip freeze
RoboMachine==0.7
argparse==1.2.1
pyparsing==2.0.3
robotframework==2.8.7
wsgiref==0.1.2
```
I'm sorry about license, I'm not really experienced with that. Should I just copy-past it from other file in the project?

**Comment by mkorpela** [comment]
ok. So the basic problem is that the version number lives in the main package and this will also import pyparsing and while using it from setup then it fails to import error before even getting to dependency installation. Thanks for the bug report! I just thought that the fix was a bit odd.

**Comment by Tset-Noitamotua** [comment]
Installation fails. What am I doing wrong?

```shell
H:\>pip --version
pip 7.1.2 from C:\Python27\lib\site-packages\pip-7.1.2-py2.7.egg (python 2.7)

H:\>pip install RoboMachine
Collecting RoboMachine
  Using cached RoboMachine-0.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "c:\users\d_waew\appdata\local\temp\pip-build-6aszep\RoboMachine\setup.py", line 6, in <module>
        import robomachine
      File "robomachine\__init__.py", line 16, in <module>
        from parsing import parse
      File "robomachine\parsing.py", line 15, in <module>
        from pyparsing import *
    ImportError: No module named pyparsing

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\path_to_temp_dir\temp\pip-build-6aszep\RoboMachine
```

Do I have to install 'pyparsing' manually?

**Comment by Tset-Noitamotua** [comment]
Yes, I had to install 'pyparsing' myself:

```shell
H:\>pip install pyparsing
Collecting pyparsing
  Downloading pyparsing-2.0.3-py2.py3-none-any.whl
Installing collected packages: pyparsing
Successfully installed pyparsing-2.0.3

H:\>pip install RoboMachine
Collecting RoboMachine
  Using cached RoboMachine-0.7.tar.gz
Requirement already satisfied (use --upgrade to upgrade): pyparsing in c:\python27\lib\site-packages (from RoboMachine)
Collecting argparse (from RoboMachine)
  Downloading argparse-1.3.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): robotframework in c:\python27\lib\site-packages (from RoboMachine)
Installing collected packages: argparse, RoboMachine
  Running setup.py install for RoboMachine
Successfully installed RoboMachine-0.7 argparse-1.3.0
```

**Comment by mkorpela** [comment]
@Tset-Noitamotua thanks for the report,

At least on my machine pyparsing dependency gets installed when installing through pip.

I tried with pip 1.7.2

I'll leave this issue open if someone else has similar problems.
But currently I'm unable to reproduce the problem.
